[package]
name = "muck"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
git2 = "0.20.2"
human_ids = "0.1.1"
petname = "2.0.2"
